### PR TITLE
added my projects

### PR DESCRIPTION
**Pull request by roymacdonald**
Hi @alexdmiller 
I added two projects I did while at SFPC.
One of these has a lot of pictures which are just debug views, the central part of the documentation is the video.
I noticed that in the `static/img/projects/`folder there are a lot of folders with peoples names. I felt that it would be tidier if I added a folder with my name and then the project name, instead of simply the project name. Maybe it could be a good idea to add another field to the project's Front Matter (the stuff between at the beginning of the `.md` file) which specifies the path to the images folder for the project.
I made my personal portfolio on markdown and jekyll so I now a few stuff about it. Let me know if you need help with it.
Best.

### CODE REVIEW

**Comment by alexdmiller** [comment]
All of the folders with people's names are confusing. Those are an artifact of my sorting process. They are temporary and will be removed.

The goal is to limit the amount of front matter necessary. I think it's easiest if the image directory path corresponds exactly to the path of the project markdown file.

**Comment by roymacdonald** [comment]
Well, if those folders are going to disappear it makes sense what you say. Maybe then in the instructions you should stress that the folder name should be exactly the same as the project's `.md` file. I'll update my PR

**Comment by alexdmiller** [comment]
Good point re: the instructions, I've added that text. Thanks!

**Comment by roymacdonald** [comment]
done

**Comment by alexdmiller** [comment]
Thanks! Do you have any images for your new-york-city-is-flat project? It would be nice to have one to use in the directory of projects.

**Comment by roymacdonald** [comment]
Just added one. :)

**Comment by alexdmiller** [comment]
Thank you!!

**Pull request merged**
